Update goldcoinj to version with modern dependencies
Uses goldcoinj commit 373640fe2c which includes:
- Guava 33.4.0-android (was 18.0)
- OkHttp 4.12.0 (was 2.7.2)

This fixes the NoSuchMethodError in Futures.transform() that was
preventing BlockchainService from starting and connecting to peers.